#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE ROOT

### install this system ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown apache:apache "$appdir" -R

### rename fetch cgi ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
[ -e "/home/rockey/rnd" ] && rnd=$(cat /home/rockey/rnd) # remove on release!!!
mv "fetch" "fetch_$rnd.cgi"

### pull article repo ###
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown apache:apache "$contentsdir" -R

echo "call fetch_$rnd.cgi from GitHub"
